# Target configurations for Helm Release deployment of StreamingApp

replicaCount: 2

frontend:
  replicaCount: 2
  image:
    repository: <AWS_ACCOUNT_ID>.dkr.ecr.<YOUR_AWS_REGION>.amazonaws.com/streaming-app-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80

backend:
  replicaCount: 2
  image:
    repository: <AWS_ACCOUNT_ID>.dkr.ecr.<YOUR_AWS_REGION>.amazonaws.com/streaming-app-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000

mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: 5.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  uri: "mongodb://mongodb-service:27017/streaming"
